In [2]:
import pandas as pd
import numpy as np
import re

## Trích xuất các món ăn từ menu

In [20]:
menu_path = 'demo_menu.xlsx'
all_dishes = []

# Đọc tất cả các sheet trong file
xl = pd.ExcelFile(menu_path)

for sheet_name in xl.sheet_names:

    # Bỏ qua header công ty
    menu_raw = pd.read_excel(menu_path, sheet_name=sheet_name, skiprows=4, header=None)
    
    # Dòng chứa ngày là dòng index 1, từ cột index 2 trở đi
    dates = menu_raw.iloc[1, 2:].values

    # Xử lý thân bảng
    menu_content = menu_raw.iloc[2:, 1:].copy()
    # Fill giá trị của cột món ăn
    menu_content.iloc[:,0] = menu_content.iloc[:,0].ffill()
    
    for i, date in enumerate(dates):
        if pd.isna(date): continue # Bỏ qua cột trống nếu có
        
        # Lấy dữ liệu của từng ngày (cột tương ứng)
        temp_menu = menu_content.iloc[:, [0, i+1]].copy()
        temp_menu.columns = ['Loại món', 'Tên món']
        temp_menu['Ngày'] = date
        all_dishes.append(temp_menu)

all_dishes[:6]

[     Loại món Tên món       Ngày
 2   Món chính     NaN 2025-12-29
 3     Món phụ     NaN 2025-12-29
 4         Xào     NaN 2025-12-29
 5        Canh     NaN 2025-12-29
 6    Món chay     NaN 2025-12-29
 7    Món chay     NaN 2025-12-29
 8    Món soup     NaN 2025-12-29
 9   Món chính     NaN 2025-12-29
 10    Món phụ     NaN 2025-12-29
 11        Xào     NaN 2025-12-29
 12       Canh     NaN 2025-12-29
 13       Canh     NaN 2025-12-29
 14       Canh     NaN 2025-12-29,
      Loại món Tên món       Ngày
 2   Món chính     NaN 2025-12-30
 3     Món phụ     NaN 2025-12-30
 4         Xào     NaN 2025-12-30
 5        Canh     NaN 2025-12-30
 6    Món chay     NaN 2025-12-30
 7    Món chay     NaN 2025-12-30
 8    Món soup     NaN 2025-12-30
 9   Món chính     NaN 2025-12-30
 10    Món phụ     NaN 2025-12-30
 11        Xào     NaN 2025-12-30
 12       Canh     NaN 2025-12-30
 13       Canh     NaN 2025-12-30
 14       Canh     NaN 2025-12-30,
      Loại món Tên món       Ngày
 2   Món chính     NaN 2025-12-31
 3     Món phụ     NaN 2025-12-31
 4         Xào     NaN 2025-12-31
 5        Canh     NaN 2025-12-31
 6    Món chay     NaN 2025-12-31
 7    Món chay     NaN 2025-12-31
 8    Món soup     NaN 2025-12-31
 9   Món chính     NaN 2025-12-31
 10    Món phụ     NaN 2025-12-31
 11        Xào     NaN 2025-12-31
 12       Canh     NaN 2025-12-31
 13       Canh     NaN 2025-12-31
 14       Canh     NaN 2025-12-31,
      Loại món Tên món       Ngày
 2   Món chính     NaN 2026-01-01
 3     Món phụ     NaN 2026-01-01
 4         Xào     NaN 2026-01-01
 5        Canh     NaN 2026-01-01
 6    Món chay     NaN 2026-01-01
 7    Món chay     NaN 2026-01-01
 8    Món soup     NaN 2026-01-01
 9   Món chính     NaN 2026-01-01
 10    Món phụ     NaN 2026-01-01
 11        Xào     NaN 2026-01-01
 12       Canh     NaN 2026-01-01
 13       Canh     NaN 2026-01-01
 14       Canh     NaN 2026-01-01,
      Loại món             Tên món       Ngày
 2   Món chính         Bò nấu gừng 2026-01-02
 3     Món phụ       Đậu nướng tỏi 2026-01-02
 4         Xào    Món sốt lá chanh 2026-01-02
 5        Canh      Thịt kho sả ớt 2026-01-02
 6    Món chay        Rau rim gừng 2026-01-02
 7    Món chay   Thịt xào thập cẩm 2026-01-02
 8    Món soup      Rau chiên gừng 2026-01-02
 9   Món chính    Thịt kho mỡ hành 2026-01-02
 10    Món phụ       Đậu chiên tỏi 2026-01-02
 11        Xào      Cá kho mỡ hành 2026-01-02
 12       Canh  Món nướng lá chanh 2026-01-02
 13       Canh                 NaN 2026-01-02
 14       Canh                 NaN 2026-01-02,
      Loại món               Tên món       Ngày
 2   Món chính       Gà sốt nước mắm 2026-01-03
 3     Món phụ         Rau chiên tỏi 2026-01-03
 4         Xào           Gà hấp gừng 2026-01-03
 5        Canh      Đậu chiên ngũ vị 2026-01-03
 6    Món chay      Đậu rim lá chanh 2026-01-03
 7    Món chay      Heo sốt nước mắm 2026-01-03
 8    Món soup     Món chiên mỡ hành 2026-01-03
 9   Món chính  Trứng chiên thập cẩm 2026-01-03
 10    Món phụ         Thịt sốt gừng 2026-01-03
 11        Xào        Bò nấu mỡ hành 2026-01-03
 12       Canh        Cá sốt mỡ hành 2026-01-03
 13       Canh                   NaN 2026-01-03
 14       Canh                   NaN 2026-01-03]

In [21]:
menu_df = pd.concat(all_dishes, ignore_index=True)
# Làm sạch dữ liệu
menu_df = menu_df.dropna(subset=['Tên món'])
menu_df['Tên món'] = menu_df['Tên món'].str.strip()

# Chuyển cột Ngay sang định dạng datetime để sắp xếp
menu_df['Ngày'] = pd.to_datetime(menu_df['Ngày'], dayfirst=True)

# Tạo cột Next Date để báo dữ liệu này bị trùng
next_dates = menu_df.groupby('Tên món')['Ngày'].shift(-1)
menu_df['Ngày trùng'] = ("trùng với ngày " + next_dates.dt.strftime('%d/%m')).where(next_dates.notna(), np.nan)
menu_df

      Loại món            Tên món       Ngày            Ngày trùng
52   Món chính        Bò nấu gừng 2026-01-02                   NaN
53     Món phụ      Đậu nướng tỏi 2026-01-02                   NaN
54         Xào   Món sốt lá chanh 2026-01-02  trùng với ngày 20/01
55        Canh     Thịt kho sả ớt 2026-01-02  trùng với ngày 28/01
56    Món chay       Rau rim gừng 2026-01-02  trùng với ngày 06/01
..         ...                ...        ...                   ...
659  Món chính  Canh sốt nước mắm 2026-02-28                   NaN
660    Món phụ    Món kho mỡ hành 2026-02-28                   NaN
661        Xào       Cá luộc gừng 2026-02-28                   NaN
662       Canh     Gà rim mỡ hành 2026-02-28                   NaN
663   Món soup       Bò nấu sả ớt 2026-02-28                   NaN

[515 rows x 4 columns]

In [22]:
# Tạo menu dict để map với file inventory
menu_dict = {}
for date_val, group in menu_df.groupby('Ngày'):
    # Chuyển ngày về định dạng chuỗi giống s_name (DD-MM-YYYY) để khớp nhau
    date_str = date_val.strftime('%d-%m-%Y')
    menu_dict[date_str] = group[['Loại món', 'Tên món', 'Ngày trùng']].reset_index(drop=True)
menu_dict

{'02-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính         Bò nấu gừng                   NaN
 1     Món phụ       Đậu nướng tỏi                   NaN
 2         Xào    Món sốt lá chanh  trùng với ngày 20/01
 3        Canh      Thịt kho sả ớt  trùng với ngày 28/01
 4    Món chay        Rau rim gừng  trùng với ngày 06/01
 5    Món chay   Thịt xào thập cẩm  trùng với ngày 05/01
 6    Món soup      Rau chiên gừng  trùng với ngày 29/01
 7   Món chính    Thịt kho mỡ hành  trùng với ngày 07/01
 8     Món phụ       Đậu chiên tỏi  trùng với ngày 20/01
 9         Xào      Cá kho mỡ hành  trùng với ngày 08/01
 10       Canh  Món nướng lá chanh  trùng với ngày 09/01,
 '03-01-2026':      Loại món               Tên món            Ngày trùng
 0   Món chính       Gà sốt nước mắm  trùng với ngày 07/01
 1     Món phụ         Rau chiên tỏi                   NaN
 2         Xào           Gà hấp gừng  trùng với ngày 05/01
 3        Canh      Đậu chiên ngũ vị  trùng với ngày 05/01
 4    Món chay      Đậu rim lá chanh                   NaN
 5    Món chay      Heo sốt nước mắm  trùng với ngày 05/01
 6    Món soup     Món chiên mỡ hành                   NaN
 7   Món chính  Trứng chiên thập cẩm  trùng với ngày 17/01
 8     Món phụ         Thịt sốt gừng                   NaN
 9         Xào        Bò nấu mỡ hành  trùng với ngày 06/01
 10       Canh        Cá sốt mỡ hành  trùng với ngày 05/01,
 '05-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính   Món luộc lá chanh  trùng với ngày 23/02
 1     Món phụ          Cá rim tỏi  trùng với ngày 23/02
 2         Xào         Gà hấp gừng  trùng với ngày 07/01
 3        Canh    Đậu chiên ngũ vị  trùng với ngày 07/01
 4    Món chay      Đậu kho ngũ vị  trùng với ngày 29/01
 5    Món chay    Heo sốt nước mắm  trùng với ngày 07/01
 6   Món chính   Thịt sốt thập cẩm  trùng với ngày 10/01
 7     Món phụ       Heo nướng tỏi  trùng với ngày 19/01
 8         Xào  Rau nướng thập cẩm  trùng với ngày 08/01
 9        Canh      Cá sốt mỡ hành  trùng với ngày 08/01
 10   Món chay    Thịt chiên sả ớt  trùng với ngày 08/01
 11   Món chay   Thịt xào thập cẩm  trùng với ngày 09/01
 12    Món sop      Thịt chiên tỏi                   NaN,
 '06-01-2026':      Loại món              Tên món            Ngày trùng
 0   Món chính         Cá hấp sả ớt  trùng với ngày 12/01
 1     Món phụ        Tôm xào sả ớt  trùng với ngày 13/01
 2         Xào    Trứng sốt mỡ hành  trùng với ngày 16/01
 3        Canh       Gà rim mỡ hành  trùng với ngày 07/01
 4    Món chay  Canh chiên nước mắm  trùng với ngày 24/02
 5   Món chính    Canh sốt nước mắm  trùng với ngày 14/01
 6     Món phụ    Thịt nấu thập cẩm  trùng với ngày 24/01
 7         Xào       Bò nấu mỡ hành  trùng với ngày 10/01
 8        Canh  Canh luộc chua ngọt  trùng với ngày 14/01
 9    Món chay         Rau rim gừng                   NaN
 10   Món chay        Heo kho sả ớt  trùng với ngày 23/01
 11    Món sop      Tôm kho mỡ hành  trùng với ngày 23/01,
 '07-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính    Thịt kho mỡ hành  trùng với ngày 21/01
 1     Món phụ    Cá kho chua ngọt  trùng với ngày 08/01
 2         Xào         Heo xào tỏi  trùng với ngày 13/01
 3        Canh      Gà rim mỡ hành  trùng với ngày 10/01
 4    Món chay      Tôm kho ngũ vị  trùng với ngày 25/02
 5    Món chay         Cá hấp gừng  trùng với ngày 25/02
 6   Món chính  Tôm chiên thập cẩm  trùng với ngày 25/02
 7     Món phụ     Gà sốt nước mắm  trùng với ngày 08/01
 8         Xào         Gà hấp gừng  trùng với ngày 12/01
 9        Canh    Đậu chiên ngũ vị  trùng với ngày 13/01
 10   Món chay  Canh chiên mỡ hành                   NaN
 11   Món chay    Heo sốt nước mắm  trùng với ngày 09/01
 12    Món sop   Rau nấu chua ngọt  trùng với ngày 27/01,
 '08-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính       Heo chiên tỏi  trùng với ngày 26/01
 1     Món phụ    Thịt chiên sả ớt  trùng với ngày 26/02
 2         Xào  Rau nướng thập cẩm  trùng với ngày 12/01
 3        Canh      Cá sốt mỡ hành  trùng với ngày 15/01
 4    Món chay     Gà sốt nước mắm  trùng với ngày 22/01
 5    Món chay   Canh nấu nước mắm  trùng với ngày 26/02
 6   Món chính         Bò xào gừng  trùng với ngày 14/01
 7     Món phụ    Trứng hấp ngũ vị                   NaN
 8         Xào      Cá kho mỡ hành  trùng với ngày 06/02
 9        Canh      Thịt nướng tỏi  trùng với ngày 17/01
 10   Món chay    Tôm sốt thập cẩm                   NaN
 11   Món chay    Cá kho chua ngọt  trùng với ngày 12/01
 12    Món sop    Tôm sốt lá chanh  trùng với ngày 19/01,
 '09-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính         Gà luộc tỏi  trùng với ngày 23/01
 1     Món phụ     Cá kho thập cẩm  trùng với ngày 03/02
 2         Xào   Bò luộc chua ngọt  trùng với ngày 14/01
 3        Canh        Tôm xào gừng  trùng với ngày 12/01
 4    Món chay   Thịt xào thập cẩm  trùng với ngày 14/02
 5    Món chay         Cá nấu gừng  trùng với ngày 09/01
 6   Món chính   Bò nướng nước mắm  trùng với ngày 17/01
 7     Món phụ    Heo sốt nước mắm  trùng với ngày 16/01
 8         Xào        Tôm rim gừng  trùng với ngày 31/01
 9        Canh  Món nướng lá chanh  trùng với ngày 14/01
 10   Món chay         Cá nấu gừng  trùng với ngày 21/01
 11   Món chay     Cá rim nước mắm  trùng với ngày 20/01
 12    Món sop   Canh sốt thập cẩm  trùng với ngày 19/01,
 '10-01-2026':      Loại món               Tên món            Ngày trùng
 0   Món chính     Thịt sốt thập cẩm  trùng với ngày 02/02
 1     Món phụ           Cá sốt gừng  trùng với ngày 28/02
 2         Xào        Bò nấu mỡ hành  trùng với ngày 24/02
 3        Canh      Heo nấu nước mắm                   NaN
 4    Món chay         Heo sốt sả ớt  trùng với ngày 29/01
 5    Món chay         Rau nướng tỏi  trùng với ngày 28/02
 6   Món chính           Bò kho gừng                   NaN
 7     Món phụ       Món kho mỡ hành  trùng với ngày 28/02
 8         Xào       Trứng xào sả ớt                   NaN
 9        Canh        Gà rim mỡ hành  trùng với ngày 15/01
 10   Món chay  Trứng nướng lá chanh                   NaN
 11   Món chay           Gà rim gừng  trùng với ngày 16/01
 12    Món sop          Bò nấu sả ớt  trùng với ngày 14/01,
 '12-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính     Canh hấp ngũ vị  trùng với ngày 11/02
 1     Món phụ     Bò kho lá chanh                   NaN
 2         Xào         Gà hấp gừng  trùng với ngày 14/01
 3        Canh        Tôm xào gừng  trùng với ngày 19/01
 4    Món chay  Rau nướng thập cẩm  trùng với ngày 16/01
 5    Món chay    Cá kho chua ngọt  trùng với ngày 24/01
 6   Món chính        Cá hấp sả ớt  trùng với ngày 20/01
 7     Món phụ   Rau xào chua ngọt  trùng với ngày 09/02
 8         Xào     Món rim mỡ hành  trùng với ngày 28/01
 9        Canh   Tôm xào chua ngọt                   NaN
 10    Món sop    Bò kho chua ngọt  trùng với ngày 24/01,
 '13-01-2026':      Loại món                Tên món            Ngày trùng
 0   Món chính           Tôm sốt gừng                   NaN
 1     Món phụ          Tôm xào sả ớt  trùng với ngày 29/01
 2         Xào            Heo xào tỏi  trùng với ngày 24/01
 3        Canh     Rau nướng lá chanh  trùng với ngày 30/01
 4    Món chay  Trứng nướng chua ngọt                   NaN
 5    Món chay       Đậu rim thập cẩm  trùng với ngày 21/01
 6   Món chính         Canh nấu sả ớt                   NaN
 7     Món phụ        Đậu luộc ngũ vị                   NaN
 8         Xào     Trứng nướng ngũ vị  trùng với ngày 02/02
 9        Canh       Đậu chiên ngũ vị  trùng với ngày 21/01
 10    Món sop       Rau nấu nước mắm  trùng với ngày 20/01,
 '14-01-2026':      Loại món              Tên món            Ngày trùng
 0   Món chính          Bò xào gừng                   NaN
 1     Món phụ       Bò hấp mỡ hành                   NaN
 2         Xào    Bò luộc chua ngọt  trùng với ngày 19/01
 3        Canh   Món nướng lá chanh  trùng với ngày 16/01
 4    Món chay      Gà xào nước mắm                   NaN
 5    Món chay          Cá xào gừng  trùng với ngày 23/01
 6   Món chính    Canh sốt nước mắm  trùng với ngày 13/02
 7     Món phụ         Gà sốt sả ớt                   NaN
 8         Xào          Gà hấp gừng  trùng với ngày 26/01
 9        Canh  Canh luộc chua ngọt  trùng với ngày 10/02
 10    Món sop         Bò nấu sả ớt  trùng với ngày 23/01,
 '15-01-2026':      Loại món            Tên món            Ngày trùng
 0   Món chính  Canh luộc mỡ hành                   NaN
 1     Món phụ   Heo kho nước mắm                   NaN
 2         Xào       Cá sốt sả ớt                   NaN
 3        Canh     Gà rim mỡ hành  trùng với ngày 03/02
 4    Món chay    Heo chiên sả ớt                   NaN
 5    Món chay        Đậu rim tỏi  trùng với ngày 22/01
 6   Món chính   Heo kho lá chanh  trùng với ngày 19/01
 7     Món phụ      Món nướng tỏi                   NaN
 8         Xào        Rau xào tỏi  trùng với ngày 20/01
 9        Canh     Cá sốt mỡ hành  trùng với ngày 14/02
 10    Món sop    Gà hấp nước mắm                   NaN,
 '16-01-2026':      Loại món               Tên món            Ngày trùng
 0   Món chính        Thịt nấu sả ớt                   NaN
 1     Món phụ      Heo sốt nước mắm  trùng với ngày 02/02
 2         Xào    Rau nướng thập cẩm  trùng với ngày 23/01
 3        Canh      Thịt rim mỡ hành  trùng với ngày 26/01
 4    Món chay           Gà rim gừng  trùng với ngày 24/01
 5    Món chay  Trứng chiên nước mắm  trùng với ngày 26/01
 6   Món chính       Cá xào lá chanh                   NaN
 7     Món phụ          Heo luộc tỏi  trùng với ngày 05/02
 8         Xào     Trứng sốt mỡ hành  trùng với ngày 17/01
 9        Canh    Món nướng lá chanh  trùng với ngày 22/01
 10    Món sop     Heo nướng mỡ hành  trùng với ngày 21/01,
 '17-01-2026':      Loại món               Tên món            Ngày trùng
 0   Món chính     Bò nướng nước mắm                   NaN
 1     Món phụ        Đậu hấp ngũ vị  trùng với ngày 20/01
 2         Xào     Trứng sốt mỡ hành  trùng với ngày 21/01
 3        Canh        Thịt nướng tỏi  trùng với ngày 17/01
 4    Món chay     Cá chiên nước mắm  trùng với ngày 30/01
 5    Món chay      Đậu nấu lá chanh                   NaN
 6   Món chính  Trứng chiên thập cẩm  trùng với ngày 20/01
 7     Món phụ     Rau sốt chua ngọt  trùng với ngày 04/02
 8         Xào       Bò chiên ngũ vị  trùng với ngày 09/02
 9        Canh        Thịt nướng tỏi  trùng với ngày 22/01
 10    Món sop     Cá chiên thập cẩm  trùng với ngày 22/01,
 '19-01-2026':      Loại món            Tên món            Ngày trùng
 0   Món chính         Cá hấp tỏi                   NaN
 1     Món phụ      Heo nướng tỏi  trùng với ngày 27/01
 2         Xào  Bò luộc chua ngọt  trùng với ngày 23/01
 3        Canh       Đậu luộc tỏi                   NaN
 4    Món chay        Đậu hấp tỏi                   NaN
 5    Món chay      Bò rim ngũ vị                   NaN
 6    Món Soup  Canh sốt thập cẩm  trùng với ngày 21/01
 7   Món chính   Heo kho lá chanh  trùng với ngày 22/01
 8     Món phụ     Món chiên gừng                   NaN
 9         Xào     Đậu xào ngũ vị  trùng với ngày 09/02
 10       Canh       Tôm xào gừng  trùng với ngày 02/02
 11   Món Soup   Tôm sốt lá chanh  trùng với ngày 24/01,
 '20-01-2026':      Loại món               Tên món            Ngày trùng
 0   Món chính          Cá hấp sả ớt  trùng với ngày 27/01
 1     Món phụ         Đậu chiên tỏi  trùng với ngày 23/01
 2         Xào      Món sốt lá chanh  trùng với ngày 03/02
 3        Canh     Thịt kho thập cẩm                   NaN
 4    Món chay   Canh nướng nước mắm                   NaN
 5    Món chay       Cá rim nước mắm  trùng với ngày 12/02
 6    Món Soup      Rau nấu nước mắm  trùng với ngày 10/02
 7   Món chính  Trứng chiên thập cẩm                   NaN
 8     Món phụ        Đậu hấp ngũ vị  trùng với ngày 27/01
 9         Xào           Rau xào tỏi  trùng với ngày 21/01
 10       Canh       Heo rim mỡ hành                   NaN
 11   Món Soup     Canh hấp nước mắm                   NaN,
 '21-01-2026':      Loại món            Tên món            Ngày trùng
 0   Món chính   Thịt kho mỡ hành  trùng với ngày 07/02
 1     Món phụ      Bò kho ngũ vị                   NaN
 2         Xào        Rau xào tỏi  trùng với ngày 05/02
 3        Canh   Heo nướng ngũ vị                   NaN
 4    Món chay        Cá nấu gừng  trùng với ngày 31/01
 5    Món chay   Bò hấp chua ngọt  trùng với ngày 10/02
 6    Món Soup  Heo nướng mỡ hành  trùng với ngày 22/01
 7   Món chính     Thịt rim sả ớt                   NaN
 8     Món phụ   Đậu rim thập cẩm                   NaN
 9         Xào  Trứng sốt mỡ hành  trùng với ngày 05/02
 10       Canh   Đậu chiên ngũ vị  trùng với ngày 28/01
 11   Món Soup  Canh sốt thập cẩm  trùng với ngày 13/02,
 '22-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính     Gà sốt nước mắm  trùng với ngày 12/02
 1     Món phụ         Đậu rim tỏi  trùng với ngày 26/01
 2         Xào      Món rim ngũ vị                   NaN
 3        Canh  Món nướng lá chanh  trùng với ngày 24/01
 4    Món chay    Trứng luộc sả ớt                   NaN
 5    Món chay    Đậu sốt nước mắm                   NaN
 6    Món Soup   Cá chiên thập cẩm  trùng với ngày 26/01
 7   Món chính    Heo kho lá chanh  trùng với ngày 04/02
 8     Món phụ   Canh rim nước mắm  trùng với ngày 04/02
 9         Xào    Tôm kho nước mắm  trùng với ngày 30/01
 10       Canh      Thịt nướng tỏi  trùng với ngày 02/02
 11   Món Soup   Heo nướng mỡ hành                   NaN,
 '23-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính         Gà luộc tỏi  trùng với ngày 27/02
 1     Món phụ      Cá nấu mỡ hành  trùng với ngày 30/01
 2         Xào  Rau nướng thập cẩm  trùng với ngày 26/01
 3        Canh   Cá nướng thập cẩm  trùng với ngày 27/01
 4    Món chay       Heo kho sả ớt  trùng với ngày 03/02
 5    Món chay         Cá xào gừng  trùng với ngày 29/01
 6    Món Soup        Bò nấu sả ớt  trùng với ngày 23/01
 7   Món chính     Bò hấp thập cẩm  trùng với ngày 06/02
 8     Món phụ       Đậu chiên tỏi  trùng với ngày 30/01
 9         Xào   Bò luộc chua ngọt  trùng với ngày 03/02
 10       Canh        Bò nấu sả ớt  trùng với ngày 28/01
 11   Món Soup     Tôm kho mỡ hành  trùng với ngày 31/01,
 '24-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính    Rau nướng ngũ vị  trùng với ngày 02/02
 1     Món phụ   Thịt nấu thập cẩm  trùng với ngày 24/02
 2         Xào         Heo xào tỏi  trùng với ngày 29/01
 3        Canh  Thịt kho chua ngọt  trùng với ngày 26/01
 4    Món chay         Gà rim gừng  trùng với ngày 26/01
 5    Món chay  Món chiên thập cẩm  trùng với ngày 24/01
 6    Món Soup    Tôm sốt lá chanh  trùng với ngày 31/01
 7   Món chính  Món chiên thập cẩm                   NaN
 8     Món phụ    Cá kho chua ngọt  trùng với ngày 06/02
 9         Xào  Trứng rim thập cẩm                   NaN
 10       Canh  Món nướng lá chanh  trùng với ngày 27/01
 11   Món Soup    Bò kho chua ngọt                   NaN,
 '26-01-2026':      Loại món               Tên món            Ngày trùng
 0   Món chính       Canh nướng gừng  trùng với ngày 09/02
 1     Món phụ           Đậu rim tỏi  trùng với ngày 28/01
 2         Xào    Rau nướng thập cẩm  trùng với ngày 04/02
 3        Canh      Thịt rim mỡ hành                   NaN
 4    Món chay           Gà rim gừng  trùng với ngày 04/02
 5    Món chay  Trứng chiên nước mắm                   NaN
 6    Món soup     Cá chiên thập cẩm  trùng với ngày 10/02
 7   Món chính         Heo chiên tỏi                   NaN
 8     Món phụ     Món rim chua ngọt                   NaN
 9         Xào       Tôm nướng sả ớt  trùng với ngày 31/01
 10       Canh    Thịt kho chua ngọt  trùng với ngày 31/01
 11    Món sop           Gà hấp gừng  trùng với ngày 30/01,
 '27-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính       Heo nướng tỏi  trùng với ngày 23/02
 1     Món phụ      Đậu hấp ngũ vị  trùng với ngày 13/02
 2         Xào       Heo xào sả ớt                   NaN
 3        Canh  Món nướng lá chanh  trùng với ngày 31/01
 4    Món chay      Cá chiên sả ớt                   NaN
 5    Món soup   Rau nấu chua ngọt  trùng với ngày 05/02
 6   Món chính        Cá hấp sả ớt  trùng với ngày 24/02
 7     Món phụ   Thịt hấp lá chanh                   NaN
 8         Xào  Thịt luộc lá chanh                   NaN
 9        Canh   Cá nướng thập cẩm  trùng với ngày 04/02
 10    Món sop     Cá kho nước mắm                   NaN,
 '28-01-2026':      Loại món            Tên món            Ngày trùng
 0   Món chính   Cá rim chua ngọt                   NaN
 1     Món phụ      Canh nấu gừng                   NaN
 2         Xào   Gà nấu chua ngọt                   NaN
 3        Canh     Thịt kho sả ớt  trùng với ngày 30/01
 4    Món chay       Bò nướng tỏi                   NaN
 5    Món chay      Món luộc gừng                   NaN
 6    Món soup   Heo chiên ngũ vị  trùng với ngày 11/02
 7   Món chính  Tôm luộc nước mắm  trùng với ngày 31/01
 8     Món phụ        Đậu rim tỏi  trùng với ngày 09/02
 9         Xào    Món rim mỡ hành  trùng với ngày 12/02
 10       Canh   Đậu chiên ngũ vị  trùng với ngày 29/01
 11    Món sop       Bò nấu sả ớt  trùng với ngày 04/02,
 '29-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính       Món kho sả ớt  trùng với ngày 04/02
 1     Món phụ      Đậu kho ngũ vị  trùng với ngày 23/02
 2         Xào         Heo xào tỏi  trùng với ngày 29/01
 3        Canh    Đậu chiên ngũ vị  trùng với ngày 05/02
 4    Món chay       Tôm xào sả ớt  trùng với ngày 24/02
 5    Món chay       Heo sốt sả ớt  trùng với ngày 28/02
 6    Món soup      Rau chiên gừng  trùng với ngày 09/02
 7   Món chính      Bò chiên sả ớt                   NaN
 8     Món phụ    Bò sốt chua ngọt                   NaN
 9         Xào         Heo xào tỏi  trùng với ngày 07/02
 10       Canh         Cá xào gừng  trùng với ngày 05/02
 11    Món sop  Cá nướng chua ngọt                   NaN,
 '30-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính     Bò nấu lá chanh                   NaN
 1     Món phụ  Canh luộc nước mắm                   NaN
 2         Xào         Gà hấp gừng  trùng với ngày 02/02
 3        Canh  Rau nướng lá chanh                   NaN
 4    Món chay   Cá chiên nước mắm                   NaN
 5    Món chay       Thịt hấp gừng                   NaN
 6    Món soup  Rau luộc chua ngọt                   NaN
 7   Món chính      Thịt kho sả ớt                   NaN
 8     Món phụ       Đậu chiên tỏi  trùng với ngày 07/02
 9         Xào    Tôm kho nước mắm  trùng với ngày 23/02
 10       Canh  Gà nướng chua ngọt  trùng với ngày 12/02
 11    Món sop      Cá nấu mỡ hành  trùng với ngày 06/02,
 '31-01-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính   Tôm luộc nước mắm                   NaN
 1     Món phụ       Gà nấu ngũ vị                   NaN
 2         Xào     Tôm nướng sả ớt                   NaN
 3        Canh  Thịt kho chua ngọt  trùng với ngày 06/02
 4    Món chay         Cá nấu gừng  trùng với ngày 11/02
 5    Món chay        Rau xào gừng                   NaN
 6    Món soup     Tôm kho mỡ hành  trùng với ngày 04/02
 7   Món chính  Trứng sốt nước mắm                   NaN
 8     Món phụ   Thịt hấp nước mắm                   NaN
 9         Xào        Tôm rim gừng  trùng với ngày 26/02
 10       Canh  Món nướng lá chanh  trùng với ngày 02/02
 11    Món sop    Tôm sốt lá chanh  trùng với ngày 03/02,
 '02-02-2026':      Loại món             Tên món            Ngày trùng
 0   Món chính   Thịt sốt thập cẩm  trùng với ngày 25/02
 1     Món phụ    Heo sốt nước mắm  trùng với ngày 23/02
 2         Xào         Gà hấp gừng  trùng với ngày 07/02
 3        Canh  Món nướng lá chanh  trùng với ngày 05/02
 4    Món chay  Trứng sốt lá chanh  trùng với ngày 14/02

## Làm việc với file inventory

In [23]:
# 1. Đọc file (đọc thô toàn bộ để tìm vị trí trước)
inventory_path = 'demo_inventory.xlsx'
inv_raw = pd.read_excel(inventory_path, header=None)
inv_raw

,0,1,2,3,4,5,6,7,8
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,"GLOBO-FEAST CATERING SOLUTIONS CO., LTD",NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,"Address: No. 123 Nowhere Lane, Void District, ...",NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Tel: +84 (0) 123 456 789,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3101,28.0,2.0,56,Cá sông rim chua ngọt (Mẫu 129),kg,NaN,0.9,NaN,NaN
3102,28.0,2.0,57,Mì căn luộc chua ngọt (Mẫu 135),kg,NaN,2.0,NaN,NaN
3103,28.0,2.0,58,NaN,NaN,NaN,NaN,NaN,NaN
3104,28.0,2.0,59,NaN,NaN,NaN,NaN,NaN,NaN
3105,NaN,NaN,Storekeeper,NaN,Receiver,NaN,NaN,Delivered by,NaN

In [24]:
results_storage = {}

# 1. Tìm vị trí các ngày trong file inventory
day_indices = []
for idx, row in inv_raw.iterrows():
    cell_val = str(row[2]) 
    if re.search(r'Ngày\s+\d+\s+tháng\s+\d+\s+năm\s+\d+', cell_val):
        day_indices.append(idx)
day_indices.append(len(inv_raw))

print(f"Tìm thấy {len(day_indices)-1} ngày trong file Kho.")

Tìm thấy 44 ngày trong file Kho.

In [25]:
# 2. Vòng lặp xử lý và combine với menu
for i in range(len(day_indices) - 1):
    start_pos = day_indices[i]
    end_pos = day_indices[i+1]
    
    # Lấy tên ngày (Dùng làm Key khớp với menu_dict)
    raw_date_str = str(inv_raw.iloc[start_pos, 2])
    match = re.search(r'(\d+)\s+tháng\s+(\d+)\s+năm\s+(\d+)', raw_date_str)
    if match:
        # Tạo s_name đúng định dạng DD-MM-YYYY (VD: 10-02-2026)
        s_name = f"{match.group(1).zfill(2)}-{match.group(2).zfill(2)}-{match.group(3)}"

    # Xử lý dữ liệu xuất kho
    inv_daily = inv_raw.iloc[start_pos:end_pos, 2:].copy()
    
    try:
        # Dòng thứ 3 sau ngày tháng là dòng dữ liệu
        inv_daily.columns = inv_daily.iloc[2]
        inv_daily = inv_daily.iloc[3:].copy()
        inv_daily = inv_daily.dropna(axis=1, how='all')
        inv_daily = inv_daily.reset_index(drop=True)
        
        # Kết hợp với menu dict tạo từ trước đó
        if s_name in menu_dict:
            df_menu = menu_dict[s_name] # Lấy món ăn đã chuẩn bị từ trước
            
            # Tạo khoảng trống giữa 2 bảng (1 cột trắng)
            spacer = pd.DataFrame({' ': [''] * max(len(inv_daily), len(df_menu))})
            
            # Ghép ngang: Kho + Trống + Menu
            # Dùng reset_index để đảm bảo các dòng khớp nhau từ trên xuống
            combined = pd.concat([
                inv_daily.reset_index(drop=True), 
                spacer.reset_index(drop=True), 
                df_menu.reset_index(drop=True)
            ], axis=1)
            status = "Menu founded"
        else:
            combined = inv_daily
            status = "No menu founded"

        # Lưu kết quả đã combine vào kho tạm
        results_storage[s_name] = combined
        print(f"{s_name}: {status}")

    except Exception as e:
        print(f"Eror occur while doing {s_name}: {e}")

02-01-2026: Menu founded
03-01-2026: Menu founded
05-01-2026: Menu founded
06-01-2026: Menu founded
07-01-2026: Menu founded
08-01-2026: Menu founded
09-01-2026: Menu founded
10-01-2026: Menu founded
12-01-2026: Menu founded
13-01-2026: Menu founded
14-01-2026: Menu founded
15-01-2026: Menu founded
16-01-2026: Menu founded
17-01-2026: Menu founded
19-01-2026: Menu founded
20-01-2026: Menu founded
21-01-2026: Menu founded
22-01-2026: Menu founded
23-01-2026: Menu founded
24-01-2026: Menu founded
26-01-2026: Menu founded
27-01-2026: Menu founded
28-01-2026: Menu founded
29-01-2026: Menu founded
30-01-2026: Menu founded
31-01-2026: Menu founded
02-02-2026: Menu founded
03-02-2026: Menu founded
04-02-2026: Menu founded
05-02-2026: Menu founded
06-02-2026: Menu founded
07-02-2026: Menu founded
09-02-2026: Menu founded
10-02-2026: Menu founded
11-02-2026: Menu founded
12-02-2026: Menu founded
13-02-2026: Menu founded
14-02-2026: Menu founded
23-02-2026: Menu founded
24-02-2026: Menu founded
25-02-2026: Menu founded
26-02-2026: Menu founded
27-02-2026: Menu founded
28-02-2026: Menu founded

In [26]:
# Tên file xuất ra
final_filename = 'Inventory_Menu_Integration.xlsx'

# Bắt đầu ghi từ bộ nhớ ra file
with pd.ExcelWriter(final_filename, engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    for s_name, data in results_storage.items():
        # Ghi dữ liệu vào sheet
        data.to_excel(writer, index=False, sheet_name=s_name)
        print(f'Data: {s_name} has been exported successfully')

print(f"Done: {final_filename}")

Data: 02-01-2026 has been exported successfully
Data: 03-01-2026 has been exported successfully
Data: 05-01-2026 has been exported successfully
Data: 06-01-2026 has been exported successfully
Data: 07-01-2026 has been exported successfully
Data: 08-01-2026 has been exported successfully
Data: 09-01-2026 has been exported successfully
Data: 10-01-2026 has been exported successfully
Data: 12-01-2026 has been exported successfully
Data: 13-01-2026 has been exported successfully
Data: 14-01-2026 has been exported successfully
Data: 15-01-2026 has been exported successfully
Data: 16-01-2026 has been exported successfully
Data: 17-01-2026 has been exported successfully
Data: 19-01-2026 has been exported successfully
Data: 20-01-2026 has been exported successfully
Data: 21-01-2026 has been exported successfully
Data: 22-01-2026 has been exported successfully
Data: 23-01-2026 has been exported successfully
Data: 24-01-2026 has been exported successfully
Data: 26-01-2026 has been exported successfully
Data: 27-01-2026 has been exported successfully
Data: 28-01-2026 has been exported successfully
Data: 29-01-2026 has been exported successfully
Data: 30-01-2026 has been exported successfully
Data: 31-01-2026 has been exported successfully
Data: 02-02-2026 has been exported successfully
Data: 03-02-2026 has been exported successfully
Data: 04-02-2026 has been exported successfully
Data: 05-02-2026 has been exported successfully
Data: 06-02-2026 has been exported successfully
Data: 07-02-2026 has been exported successfully
Data: 09-02-2026 has been exported successfully
Data: 10-02-2026 has been exported successfully
Data: 11-02-2026 has been exported successfully
Data: 12-02-2026 has been exported successfully
Data: 13-02-2026 has been exported successfully
Data: 14-02-2026 has been exported successfully
Data: 23-02-2026 has been exported successfully
Data: 24-02-2026 has been exported successfully
Data: 25-02-2026 has been exported successfully
Data: 26-02-2026 has been exported successfully
Data: 27-02-2026 has been exported successfully
Data: 28-02-2026 has been exported successfully
Done: Inventory_Menu_Integration.xlsx